export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

function getRandomInt(count: number) {
  return Math.floor(Math.random() * count);
}

export default function ProductDetailsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const random = getRandomInt(2);

  if (random === 1) throw new Error("Opps product not available");

  return (
    <>
      {children}

      <h3>Features Products</h3>
    </>
  );
}
