import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "My Next App - Something New is Comming",
    absolute: "",
    template: "%s | Something",
  },
  // title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            padding: "1rem",
            backgroundColor: "lightblue",
          }}
        >
          <h3>Header</h3>
        </header>

        {children}

        <footer
          style={{
            padding: "1rem",
            backgroundColor: "ghostwhite",
          }}
        >
          <h3>Footer</h3>
        </footer>
      </body>
    </html>
  );
}
